name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins build
        run: |
          curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
               -X POST "${{ secrets.JENKINS_URL }}/job/API%20Testing%20Pipeline/build?token=rest_Api_Token"
      - name: "Code checkout"
        uses: actions/checkout@v5

      - name: "Install node js"
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: "Install k6"
        uses: grafana/setup-k6-action@v1
      
      - name: "Run performance testing"
        run: npm run performance-test

      - name: "docker version"
        run: docker --version

      - name: "Start Application"
        run: npm run start

      - name: "Security testing with owasp zap"
        run: |
             docker run -t owasp/zap2docker-stable zap-baseline.py \
             -t http://host.docker.internal:3000 \
             -r zap_report.html
      - name: "Report generate" 
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html