name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins build
        run: |
          curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
               -X POST "${{ secrets.JENKINS_URL }}/job/API%20Testing%20Pipeline/build?token=rest_Api_Token"
      - name: "Code checkout"
        uses: actions/checkout@v5

      - name: "Install node js"
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: "Install k6"
        uses: grafana/setup-k6-action@v1
      
      - name: "Run performance testing"
        run: npm run performance-test

      - name: "docker version"
        run: docker --version